# Generated by Django 4.0b1 on 2021-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_created_on_customer_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='AFM'),
        ),
    ]
